//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HastaneGDB.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOKTORLAR
    {
        public int DOKTORNO { get; set; }
        public string AD_SOYAD { get; set; }
        public string POLIKLINIK { get; set; }
        public byte[] FOTO { get; set; }
        public string E_MAIL { get; set; }
        public Nullable<bool> IZINLIMI { get; set; }
        public Nullable<int> DR_ID { get; set; }
    }
}
