//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HastaneGDB.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIRIS
    {
        public int NUM { get; set; }
        public Nullable<int> ID { get; set; }
        public string TCNO { get; set; }
        public string SIFRE { get; set; }
        public string ADSOYAD { get; set; }
    }
}
