//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HastaneGDB.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GUNLUKIZIN
    {
        public int IZIN_ID { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string ACIKLAMA { get; set; }
        public string AD_SOYAD { get; set; }
        public string POLIKLINIK { get; set; }
        public string AKTAR_AD_SOYAD { get; set; }
    }
}
