//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HastaneGDB.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HASTA
    {
        public int HASTANO { get; set; }
        public string TCNO { get; set; }
        public string ADI_SOYADI { get; set; }
        public string POLIKLINIK { get; set; }
        public string DOKTORADI { get; set; }
        public string ADRES { get; set; }
        public string TEL { get; set; }
        public Nullable<bool> SSKMI { get; set; }
        public Nullable<bool> RANDEVUMU { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<System.TimeSpan> SAAT { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<bool> BAKILDIMI { get; set; }
        public Nullable<int> KONTROLGUNU { get; set; }
    }
}
