//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HastaneGDB.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HASTANEPROJEEntities : DbContext
    {
        public HASTANEPROJEEntities()
            : base("name=HASTANEPROJEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DOKTORLAR> DOKTORLAR { get; set; }
        public virtual DbSet<GIRIS> GIRIS { get; set; }
        public virtual DbSet<HASTA> HASTA { get; set; }
        public virtual DbSet<IZIN> IZIN { get; set; }
        public virtual DbSet<GUNLUKIZIN> GUNLUKIZIN { get; set; }
    }
}
